# Serial bus for MAVLink communication with flight controller
[[bus]]
id = "serial0"
type = "serial"
# Set path to "auto" to automatically detect flight controller via MAVLink HEARTBEAT
# Or specify a manual path:
#   macOS: /dev/cu.usbmodem01 or /dev/cu.usbserial-*
#   Linux: /dev/ttyACM0 or /dev/ttyUSB0
path = "auto"

# Optional: I2C bus for local sensors (only needed if you have I2C sensors)
# [[bus]]
# id = "i2c0"
# type = "i2c"
# path = "/dev/i2c-0"
