# Commented out - no I2C sensor connected
# [[sensor]]
# id = "imu0"
# driver = "icm42688p"
# bus = "i2c0"
# address = 0x69
# frequency = 100

# Flight controller sensors via MAVLink
[[sensor]]
id = "fc_imu"
driver = "mavlink_imu"
bus = "serial0"
address = 0x00  # Virtual address (not used for MAVLink)
frequency = 100

[[sensor]]
id = "fc_baro"
driver = "mavlink_baro"
bus = "serial0"
address = 0x01  # Virtual address
frequency = 50

[[sensor]]
id = "fc_mag"
driver = "mavlink_mag"
bus = "serial0"
address = 0x02  # Virtual address
frequency = 50
